services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin